Check common failure cases and pass options to cabal.
This closes #5.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,22 @@
-#!/bin/sh
-if [[ -z "$(which cabal)" ]]; then
+#!/bin/bash
+[ ! -z "$(which cc)" ] || (
+    echo "cc not found!"
+    exit 1
+)
+
+[ ! -z "$(which cabal)" ] || (
     echo "cabal executable not found in path!"
     exit 1
-fi
-cabal configure
+)
+
+cat > xtest_test.c <<EOF
+#include <X11/extensions/XTest.h>
+int main() { return 0; }
+EOF
+cc -o test_test xtest_test.c && ls test_test >/dev/null && ./test_test || (
+    echo "libxtst-dev not installed!"
+    exit 1
+)
+rm xtest_test.c test_test
+
+cabal configure $@
