Switch out `runhaskell Setup.hs` for `cabal`.
This allows building of the software on powerpc as well as being more
idiomatic.

Closes: #4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,2 +1,6 @@
 #!/bin/sh
-runhaskell Setup.hs configure
+if [[ -z "$(which cabal)" ]]; then
+    echo "cabal executable not found in path!"
+    exit 1
+fi
+cabal configure
